pipeline {
    agent any

    environment {
        // Change this to your real GitHub repo URL
        GIT_REPO_URL = 'https://github.com/etzhaella/EllaHalevvy_CICD_PracticalExam.git'

        // Docker Hub image (must be lowercase)
        IMAGE_NAME   = 'etzhaella/flask-aws-monitor'
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: "${GIT_BRANCH}", url: "${GIT_REPO_URL}"
            }
        }

        stage('Parallel Checks') {
            parallel {

                stage('Linting') {
                    steps {
                        // MOCK commands (allowed by the exam)
                        sh '''
                            echo "Running Python linting with flake8 (mock)"
                            echo "Running Shell linting with shellcheck (mock)"
                            echo "Running Dockerfile linting with hadolint (mock)"
                        '''
                    }
                }

                stage('Security Scan') {
                    steps {
                        // MOCK commands (allowed by the exam)
                        sh '''
                            echo "Running Bandit security scan for Python (mock)"
                            echo "Running Trivy security scan for Docker image (mock)"
                        '''
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    echo "Building Docker image from app/Dockerfile"
                    docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} ./app
                    docker tag ${IMAGE_NAME}:${BUILD_NUMBER} ${IMAGE_NAME}:latest
                '''
            }
        }

        stage('Push to Docker Hub') {
            steps {
                // dockerhub-creds = username+token stored in Jenkins Credentials
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'etzhaella'
                    passwordVariable: 'DOCKERHUB_PASSWORD'
                )]) {
                    sh '''
                        echo "Login to Docker Hub"
                        echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

                        echo "Pushing Docker image to Docker Hub"
                        docker push ${IMAGE_NAME}:${BUILD_NUMBER}
                        docker push ${IMAGE_NAME}:latest

                        echo "Logout from Docker Hub"
                        docker logout
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed! Check logs for details.'
        }
    }
}
